export const ROLE_CODES: Record<string, string> = {
  "Software Engineer": "SWE",
  "Frontend Developer": "FED",
  "Backend Developer": "BED",
  "Full Stack Developer": "FSD",
  "Web Developer": "WBD",
  "Mobile App Developer": "MAD",
  "Android Developer": "AND",
  "iOS Developer": "IOS",
  "React Developer": "RCT",
  "Next.js Developer": "NXD",
  "Node.js Developer": "NOD",
  "Python Developer": "PYD",
  "Java Developer": "JAV",
  "C++ Developer": "CPP",
  "AI/ML Engineer": "AIM",
  "Data Scientist": "DST",
  "Data Analyst": "DAN",
  "DevOps Engineer": "DOP",
  "Cloud Engineer": "CLD",
  "Cyber Security": "CSE",
  "Ethical Hacker": "ETH",
  "Blockchain Developer": "BCD",
  "Game Developer": "GMD",
  "UI/UX Designer": "UXD",
  "Product Designer": "PRD",
  "Graphic Designer": "GRD",
  "Motion Designer": "MOD",
  "Video Editor": "VED",
  "3D Artist": "ART",
  "QA Engineer": "QAE",
  "Test Automation Engineer": "TAE",
  "Database Engineer": "DBE",
  "System Engineer": "SYE",
  "ERP Developer": "ERP",
  "API Developer": "APD",
  "Embedded Systems Engineer": "ESE",
  "IoT Developer": "IOT",
  "AR/VR Developer": "ARV",
  "Technical Research Intern": "TRI",
  "Product Engineering & Design": "PED",

  "Human Resources": "HRS",
  "Operations Executive": "OPS",
  "Marketing Intern": "MKT",
  "Sales Executive": "SLS",
  "Business Development": "BDE",
  "Content Writer": "CWT",
  "Social Media Manager": "SMM",
  "Talent Acquisition": "TAC",
  "Project Coordinator": "PJC",
  "Customer Support": "CSP"
};
